schemaVersion = 1

[catalogs]
disabledIdentifiers = [
    'TunaAutomation.QuickActionsCatalog',
    'TunaAutomation.ScriptsCatalog',
    'TunaCore.FinderFavoritesCatalog',
    'TunaCore.RunningProcessesCatalog',
    'TunaDevices.DevicesCatalog',
    'TunaEmoji.EmojiCatalog',
    'TunaNotes.NotesSearchCatalog',
    'TunaObsidian.ObsidianNotesCatalog',
    'TunaObsidian.ObsidianSearchCatalog',
    'TunaObsidian.ObsidianVaultsCatalog',
    'TunaReminders.RemindersSearchCatalog',
    'TunaSafari.SafariActionsCatalog',
    'TunaSafari.SafariBookmarksCatalog',
    'TunaSafari.SafariBookmarksSearchCatalog',
    'TunaSafari.SafariFavoritesCatalog',
    'TunaSafari.SafariFavoritesSearchCatalog',
    'TunaSafari.SafariMetaCatalog',
    'TunaSafari.SafariReadingListCatalog',
    'TunaSafari.SafariReadingListSearchCatalog'
]
disabledItemKeys = []
sortOrders = []

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256

    [hotkeys.app.leaderMode]
    carbonKeyCode = 6
    carbonModifiers = 4096

[[leaderMode.bindings]]
iconPath = '/Applications/Arc.app'
key = 'w'

    [[leaderMode.bindings.children]]
    key = 'w'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Arc/Open'

    [[leaderMode.bindings.children]]
    key = 'c'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Google%20Chrome/Open'

    [[leaderMode.bindings.children]]
    key = 's'
    url = 'tuna://run/TunaCore.SystemApplicationsCatalog.Safari/Open'

[[leaderMode.bindings]]
iconPath = 'person.2.fill'
key = 'a'
label = 'Messages'

    [[leaderMode.bindings.children]]
    key = 'w'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.WhatsApp/Open'

    [[leaderMode.bindings.children]]
    key = 'a'
    url = 'tuna://run/TunaCore.SystemApplicationsCatalog.Messages/Open'

[[leaderMode.bindings]]
key = 'c'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Slack/Open'

[[leaderMode.bindings]]
key = 'z'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.zoom.us/Open'

[[leaderMode.bindings]]
key = 'm'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Spotify/Open'

[[leaderMode.bindings]]
key = 'n'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Craft/Open'

[[leaderMode.bindings]]
iconPath = '/System/Applications/Mail.app'
key = 'e'

    [[leaderMode.bindings.children]]
    key = 'e'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Shortwave/Open'

[[leaderMode.bindings]]
key = 'p'
url = 'tuna://run/Tuna.Internal.RecentObjectsCatalog.1Password/Open'

[settings]
leaderModeCheatsheetBehavior = 'always'
leaderModeCheatsheetExpandGroups = true
themeIdentifier = 'com.brnbw.tuna.themes.default'
typingTimeoutDuration = 0.5

[[smartLinks.entries]]
enabled = true
name = 'Google'
template = 'https://www.google.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Stack Overflow'
template = 'https://stackoverflow.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Wikipedia'
template = 'https://en.wikipedia.org/wiki/Special:Search?search={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'YouTube'
template = 'https://www.youtube.com/results?search_query={{input}}'

[[catalogSettings]]
catalogIdentifier = 'TunaCore.TextActionsCatalog'

    [catalogSettings.values]
    TextActionsFileExtension = 'txt'

[[catalogSettings]]
catalogIdentifier = 'TunaEmoji.EmojiCatalog'

    [catalogSettings.values]
    EmojiSkinTone = 'default'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'custom:5000BA'